name: 'Install Procursus'
description: 'Install the Procursus toolchain'
author: 'beerpsi'

inputs:
  packages:
    description: 'Space-delimited list of packages to install after bootstrapping'
    required: false
    default: null
  cache:
    description: 'Cache Procursus installation for faster bootstrapping next run'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      id: procursus-cache
      with:
        path: /opt/procursus
        key: ${{ runner.os }}-procursus
      
    - name: Downloading bootstrap
      shell: bash
      if: steps.procursus-cache.outputs.cache-hit != 'true'
      run: curl -L https://apt.procurs.us/bootstrap_darwin-amd64.tar.zst -o bootstrap.tar.zst
      
    - name: Extracting and installing bootstrap
      shell: bash
      if: steps.procursus-cache.outputs.cache-hit != 'true'
      run: |
        zstd -d bootstrap.tar.zst
        sudo gtar -xpkf bootstrap.tar -C /
        
    - name: Adding Procusus to PATH
      shell: bash
      run: |
        echo "/opt/procursus/bin:/opt/procursus/sbin:/opt/procursus/games" >> $GITHUB_PATH
        echo "CPATH='$CPATH:/opt/procursus/include'" >> $GITHUB_ENV
        echo "LIBRARY_PATH='$LIBRARY_PATH:/opt/procursus/lib'" >> $GITHUB_ENV  
        
    - name: Updating bootstrap
      shell: bash
      run: |
        sudo apt-get -y update
        sudo apt-get -y dist-upgrade || :

    - name: Install packages
      shell: bash
      if: inputs.packages
      run: |
        sudo apt-get install -y ${{ inputs.packages }}
        

branding:
  icon: download-cloud
  color: purple
